tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "gh"
brew "git"
brew "glib"
brew "libpng"
brew "neovim"
brew "nvm"
brew "python@3.8", link: false
brew "python@3.9"
brew "tmux"
cask "docker"
cask "slack"
cask "spectacle"
cask "visual-studio-code"
